name: Upload to KeyCDN

on: workflow_dispatch

jobs:
  ftp-upload:
    name: 🎉 Upload
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Update db.json and move it all to ./build/
      run: |
        mkdir dist
        cp -R widgets/* dist/
        npm install total4
        node db.js
        cp db.json dist/db.json
        ls dist -la
        
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.3
      with:
        host: ${{ secrets.KEYCDN_SERVER }}
        username: ${{ secrets.KEYCDN_USERNAME }}
        password: ${{ secrets.KEYCDN_PASSWORD }}
        remote_folder: /cms/
        local_folder: dist